apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-ausf-config
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration
    
    configuration:
      sbi:
        scheme: http
        registerIPv4: f5gc-ausf     # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0      # Can also be an ENV.
        port: 29509
      serviceNameList:
        - nausf-auth
      nrfUri: http://f5gc-nrf:29510
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001  

  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5GC
    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #info
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: info
        ReportCaller: true
      SMF:
        debugLevel: info
        ReportCaller: true
      UDR:
        debugLevel: info
        ReportCaller: true
      UDM:
        debugLevel: info
        ReportCaller: true
      NRF:
        debugLevel: info
        ReportCaller: true
      PCF:
        debugLevel: info
        ReportCaller: true
      AUSF:
        debugLevel: info
        ReportCaller: true
      N3IWF:
        debugLevel: info
        ReportCaller: true
    # library
      NAS:
        debugLevel: info
        ReportCaller: true
      FSM:
        debugLevel: info
        ReportCaller: true
      NGAP:
        debugLevel: info
        ReportCaller: true
      NamfComm:
        debugLevel: info
        ReportCaller: true
      NamfEventExposure:
        debugLevel: info
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: info
        ReportCaller: true
      NudrDataRepository:
        debugLevel: info
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: info
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: info
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: info
        ReportCaller: true
