apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-smf
  name: f5gc-smf
spec:
  type: ClusterIP
  ports:
  - name: f5gc-smf
    port: 29502
    protocol: TCP
    targetPort: 29502
  selector:
    app: f5gc-smf
