apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-smf
  labels:
    app: f5gc-smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-smf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-smf
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-smf-n4
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-smf
          image: local/f5gc-smf:v3.0.4
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            - name: f5gc-smf-config
              mountPath: /free5gc/config
            - name: f5gc-smf-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: 29502
              name: f5gc-smf
              protocol: TCP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-smf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-smf-cert
          secret:
            secretName: f5gc-smf-tls-secret
        - name: f5gc-smf-config
          configMap:
            name: f5gc-smf-config
