apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-pcf
  labels:
    app: f5gc-pcf
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-pcf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-pcf
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-pcf
          image: ghcr.io/sumichaaan/free5gc-k8s/f5gc-pcf:v3.0.4
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            - name: f5gc-pcf-config
              mountPath: /free5gc/config
            - name: f5gc-pcf-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: 29507
              name: f5gc-pcf
              protocol: TCP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-pcf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-pcf-cert
          secret:
            secretName: f5gc-pcf-tls-secret
        - name: f5gc-pcf-config
          configMap:
            name: f5gc-pcf-config
