---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-n6dummy-2-n6
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.31.101/24",
                        "gateway": "172.16.31.1"
                }
        ]
      }
    }'
