apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-n6dummy
  labels:
    app: f5gc-n6dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-n6dummy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-n6dummy
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-n6dummy-n6
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-n6dummy
          image: docker.io/centos/tools:latest
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          command:
          - /sbin/init
          securityContext:
            privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-n6dummy-sa
      terminationGracePeriodSeconds: 30
