apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-nrf
  labels:
    app: f5gc-nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-nrf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-nrf
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-nrf
          image: local/f5gc-nrf:v3.0.4
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            - name: f5gc-nrf-config
              mountPath: /free5gc/config
            - name: f5gc-nrf-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: 29510
              name: f5gc-nrf
              protocol: TCP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-nrf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-nrf-cert
          secret:
            secretName: f5gc-nrf-tls-secret
        - name: f5gc-nrf-config
          configMap:
            name: f5gc-nrf-config
