apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-udm-config
data:
  udmcfg.conf: |
    info:
      version: 1.0.0
      description: UDM initial local configuration
    
    configuration:
      serviceNameList:
        - nudm-sdm
        - nudm-uecm
        - nudm-ueau
        - nudm-ee
        - nudm-pp
      sbi:
        scheme: http
        registerIPv4: f5gc-udm     # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0      # Can also be an ENV.
        port: 29503
        tls:
          log: free5gc/udmsslkey.log
          pem: free5gc/support/TLS/udm.pem
          key: free5gc/support/TLS/udm.key
    
      udrclient:
        scheme: http
        ipv4Addr: 127.0.0.1
        port: 29504
    
      nrfclient:
        scheme: http
        ipv4Addr: 127.0.0.1
        port: 29510
      nrfUri: http://f5gc-nrf:29510
    
      # test data set from TS33501-f60 Annex C.4
      # udmProfileAHNPublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
      # udmProfileAHNPrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
      # udmProfileBHNPublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4
      # udmProfileBHNPrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
      keys:
        udmProfileAHNPublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        udmProfileAHNPrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
        udmProfileBHNPublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4
        udmProfileBHNPrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA

  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5gc
    
    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #debug
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: debug
        ReportCaller: true
      SMF:
        debugLevel: debug
        ReportCaller: true
      UDR:
        debugLevel: debug
        ReportCaller: true
      UDM:
        debugLevel: debug
        ReportCaller: true
      NRF:
        debugLevel: debug
        ReportCaller: true
      PCF:
        debugLevel: debug
        ReportCaller: true
      AUSF:
        debugLevel: debug
        ReportCaller: true
      N3IWF:
        debugLevel: debug
        ReportCaller: true
    # library
      NAS:
        debugLevel: debug
        ReportCaller: true
      FSM:
        debugLevel: debug
        ReportCaller: true
      NGAP:
        debugLevel: debug
        ReportCaller: true
      NamfComm:
        debugLevel: debug
        ReportCaller: true
      NamfEventExposure:
        debugLevel: debug
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: debug
        ReportCaller: true
      NudrDataRepository:
        debugLevel: debug
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: debug
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: debug
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: debug
        ReportCaller: true
